# Patch pour activer le Model Registry dans le DataScienceCluster
# OpenShift AI 2.22 avec dépendances MySQL et MinIO S3

apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-applications
spec:
  components:
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
