apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development 