apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-complete
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: openshift-ai
    app.kubernetes.io/part-of: openshift-ai-platform
    app.kubernetes.io/component: complete-stack
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: clusters/overlays/openshift-ai-dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncStrategy:
      apply:
        force: true   # Force kubectl apply to replace resources entirely
    automated:
      prune: false  # Don't auto-prune to avoid deleting bound PVCs and Jobs
      selfHeal: true   # Enable self-heal to automatically apply config changes
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true  # Only apply what's actually different
    - RespectIgnoreDifferences=true
    - Replace=true              # Force full replace to drop removed fields
    - ServerSideApply=true      # Use server-side apply to respect CRD schema
    retry:
      limit: 3  # Reduced retry limit
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
  ignoreDifferences:
  # Ignore Job differences that are auto-generated by Kubernetes
  - group: batch
    kind: Job
    jsonPointers:
    - /spec/selector
    - /spec/template/metadata/labels
    - /metadata/labels
    - /status
  # Ignore PVC differences for bound volumes
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
    - /metadata/annotations
    - /status
  # Ignore auto-managed fields in DataScienceCluster
  - group: datasciencecluster.opendatahub.io
    kind: DataScienceCluster
    jsonPointers:
    - /status
    - /metadata/managedFields
  # Ignore TektonConfig hub differences to avoid admission errors from removed 'categories'
  - group: operator.tekton.dev
    kind: TektonConfig
    name: config
    jsonPointers:
    - /spec/hub
