apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-complete
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: openshift-ai
    app.kubernetes.io/part-of: openshift-ai-setup
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: clusters/overlays/openshift-ai-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 