apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-operators-simple
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: openshift-ai-operators-simple
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: components/operators/rhoai-operator/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - Prune=true 