apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# OpenShift AI Core (essentiel)
- rhoai-operator/

# Service Mesh Stack (nécessaire)
- jaeger-operator.yaml
- openshift-service-mesh/
- kiali-operator/

# Serverless Stack (nécessaire)
- openshift-serverless-operator/

# GitOps (déjà installé)
- openshift-gitops-operator/

# Pipelines (nécessaire pour la démo)
- openshift-pipelines-operator/

# Note: Tous les opérateurs essentiels activés

commonLabels:
  app.kubernetes.io/part-of: openshift-ai-platform
  app.kubernetes.io/managed-by: kustomize
