# OpenShift AI Operators
# Déploiement des opérateurs nécessaires pour OpenShift AI 2.22
# 
# Utilisation:
# kubectl apply -k components/operators/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-ai-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Opérateurs en premier

# Base resources
resources:
  # Core operators for OpenShift AI
  - rhoai-operator/                    # ✅ RHODS 2.22 (essentiel)
  - jaeger-operator.yaml              # ✅ Jaeger pour Service Mesh
  - openshift-service-mesh/           # ✅ Service Mesh (essentiel)
  - kiali-operator/                   # ✅ Kiali pour Service Mesh
  - openshift-serverless-operator/    # ✅ Serverless (essentiel)
  - openshift-pipelines-operator/     # ✅ Pipelines (essentiel pour la démo)
  - openshift-gitops-operator/        # ✅ GitOps (déjà installé)

# Labels to apply to all resources
labels:
  - pairs:
      app.kubernetes.io/name: openshift-ai
      app.kubernetes.io/component: operator
      app.kubernetes.io/version: "2.22"
      app.kubernetes.io/managed-by: kustomize
      environment: development
