apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# OpenShift AI Core
- rhoai-operator/

# Service Mesh Stack (ordre important)
- jaeger-operator.yaml           # Dépendance requise pour Service Mesh
- openshift-service-mesh/
- kiali-operator/

# Serverless Stack  
- openshift-serverless-operator/

# Pipelines
- openshift-pipelines-operator/

# GitOps
- openshift-gitops-operator/

# Note: Kueue operator removed - RHOAI 2.22 manages Kueue automatically

commonLabels:
  app.kubernetes.io/part-of: openshift-ai-platform
  app.kubernetes.io/managed-by: kustomize
