apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-anyuid-scc
  labels:
    app: minio
    app.kubernetes.io/component: s3-storage
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: model-registry
subjects:
- kind: ServiceAccount
  name: minio-sa
  namespace: rhoai-model-registries
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
