apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-user-fix
  namespace: rhoai-model-registries
  labels:
    app: mysql
    app.kubernetes.io/component: database-init
    app.kubernetes.io/name: mysql-user-fix
    app.kubernetes.io/part-of: model-registry
spec:
  template:
    metadata:
      labels:
        app: mysql-user-fix
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-init
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL not ready, retrying in 5 seconds..."
            sleep 5
          done
          
          echo "MySQL is ready, configuring user authentication..."
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD << EOF
          -- Create user with mysql_native_password if not exists
          CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';
          
          -- Grant all privileges on the database
          GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';
          
          -- Update existing user to use mysql_native_password if needed
          ALTER USER '$MYSQL_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';
          
          FLUSH PRIVILEGES;
          EOF
          
          echo "User authentication configured successfully"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-database
