apiVersion: v1
kind: ConfigMap
metadata:
  name: model-registry-ssl-fix
  namespace: rhoai-model-registries
data:
  fix-ssl.sh: |
    #!/bin/bash
    # Fix SSL "packet length too long" error for Model Registry
    echo "Applying HTTP backend protocol annotation..."
    oc annotate route rhods-dashboard -n redhat-ods-applications \
      haproxy.router.openshift.io/backend-protocol=http --overwrite || true
    echo "SSL fix applied successfully"
