# Red Hat build of Kueue Operator pour gestion des queues dans RHOAI
# Intégré avec CodeFlare pour distributed workloads

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue
  namespace: openshift-operators
spec:
  channel: stable
  name: kueue
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
