# Service Mesh Control Plane pour RHOAI 2.22
# Version 2.6 avec Jaeger, Kiali et auto-mTLS
# Updated to match Service Mesh Operator 2.6.8

apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  tracing:
    type: None  # Disable external Jaeger dependency
  addons:
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  security:
    manageNetworkPolicy: true
    controlPlane:
      mtls: true
    dataPlane:
      mtls: true
      automtls: true
