apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - rhoai-model-registries
    - knative-serving
    - redhat-ods-applications
    - triton-demo
