# Secret pour la base de données du Model Registry
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db-secret
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
type: Opaque
data:
  password: cGFzc3dvcmQ=  # "password" en base64
---
# Secret pour S3/MinIO du Model Registry
apiVersion: v1
kind: Secret
metadata:
  name: model-registry-s3-secret
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
type: Opaque
data:
  access-key: bWluaW8=      # "minio" en base64
  secret-key: bWlubzEyMw==  # "minio123" en base64 