apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db-secret
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
type: Opaque
stringData:
  database-password: "TheBlurstOfTimes"
