apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: modelregistry
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
spec:
  grpc:
    port: 9090
  mysql:
    database: model_registry
    host: mysql.db-ai.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db-secret
    port: 3306
    skipDBCreation: false
    username: mlmduser
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    serviceRoute: disabled
