apiVersion: v1
kind: Namespace
metadata:
  name: db-ai
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development 