apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: db-ai
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
  type: ClusterIP 