apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: db-ai
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
type: Opaque
stringData:
  mysql-root-password: "TheBlurstOfTimes"
  mysql-user: "mlmduser"
  mysql-password: "TheBlurstOfTimes"
  mysql-database: "model_registry" 