# OpenShift AI Development Cluster
# Déploiement GitOps pour OpenShift AI 2.22 avec Service Mesh et Serverless
# 
# Utilisation:
# kubectl apply -k clusters/overlays/openshift-ai-dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-ai-dev
  
# Base resources
resources:
  # Operators first (order matters) - includes Jaeger dependency
  - ../../../components/operators/
  
  # Namespaces needed by components
  - ../../../components/instances/model-registry-namespace/base
  
  # Model Registry Dependencies (MySQL and MinIO S3)
  - ../../../components/instances/mysql-model-registry/base
  - ../../../components/instances/minio-s3-storage/base
  
  # Model Catalog Enabler (Technology Preview)
  - ../../../components/instances/model-catalog-enabler/base

  
  # Instances after operators are ready
  - ../../../components/instances/service-mesh-instance
  - ../../../components/instances/serverless-instance
  - ../../../components/instances/pipelines-instance  # ✅ Réactivé après suppression conflit Kueue
  - ../../../components/instances/rhoai-instance


# Apply these patches to customize for dev environment
 patchesStrategicMerge:
  - dev-patches.yaml
  - remove-pipelines-hub-patch.yaml

# Labels to apply to all resources
commonLabels:
  app.kubernetes.io/name: openshift-ai
  app.kubernetes.io/version: "2.22"
  app.kubernetes.io/managed-by: kustomize
  environment: development