# App of Apps - Déploie tous les composants OpenShift AI séparément
# Pattern recommandé pour grande flexibilité

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-app-of-apps
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
