apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-main
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:mouachan/openshift-ai-setup.git
    targetRevision: main
    path: clusters/overlays/openshift-ai-dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - manager
