apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhoai-model-registries

resources:
- mysql-secret.yaml
- mysql-pvc.yaml
- mysql-deployment.yaml
- mysql-service.yaml

commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: model-registry
  environment: development
