apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-auth-fix
  namespace: rhoai-model-registries
  labels:
    app: mysql-init
    app.kubernetes.io/component: database-init
    app.kubernetes.io/name: mysql-init
    app.kubernetes.io/part-of: model-registry
spec:
  template:
    metadata:
      labels:
        app: mysql-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-auth-fix
        image: mysql:8.0
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1;" > /dev/null 2>&1; do
            echo "MySQL not ready, retrying in 5 seconds..."
            sleep 5
          done
          echo "MySQL is ready, configuring authentication..."
          
          # Fix authentication plugin for registry user
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "ALTER USER 'registry'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';"
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"
          
          # Test connection
          mysql -h mysql -u registry -p$MYSQL_PASSWORD -e "SELECT 'Authentication fix completed successfully' as Status;"
          
          echo "MySQL authentication configuration completed successfully"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-password
