apiVersion: v1
kind: ConfigMap
metadata:
  name: elyra-runtime-config
  namespace: triton-demo
  labels:
    app.kubernetes.io/name: elyra-runtime-config
    app.kubernetes.io/part-of: triton-demo
data:
  # Configuration des runtime images pour Elyra
  runtime-images.yaml: |
    # Configuration des images disponibles pour les composants de pipeline
    # Ces images apparaîtront dans le dropdown "Runtime Image" des pipelines
    runtime_images:
      - display_name: "Triton Demo - Custom ML/AI Image"
        image_name: "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/triton-demo-notebook:latest"
        description: "Image personnalisée avec NumPy, Pandas, Scikit-learn, Triton Client et toutes les bibliothèques ML/AI pré-installées"
        tags: ["ml", "ai", "triton", "custom", "python3.11"]
        metadata:
          gpu: false
          cuda: false
          python_version: "3.11"
          packages:
            - "NumPy 2.3+"
            - "Pandas 2.3+"
            - "Scikit-learn 1.7+"
            - "Triton Client 2.59+"
            - "Kubeflow Pipelines 1.8+"
            - "Elyra 3.15.0"
      
      - display_name: "Standard Data Science (Fallback)"
        image_name: "quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.11-2024a-20240317-6f4c36b"
        description: "Image standard OpenShift AI pour compatibilité"
        tags: ["standard", "fallback", "python3.11"]
        metadata:
          gpu: false
          cuda: false
          python_version: "3.11"

  # Script d'initialisation du runtime basé sur le script officiel OpenShift AI
  init-runtime.py: |
    #!/usr/bin/env python3
    """
    Script pour configurer automatiquement le runtime Elyra
    Basé sur la méthode officielle OpenShift AI
    """
    import os
    import json
    import yaml
    from pathlib import Path

    # Configuration basée sur le modèle Data Science Project
    ELYRA_METADATA_DIR = os.path.expanduser("~/.local/share/jupyter/metadata")
    NAMESPACE = "triton-demo"
    CLUSTER_DOMAIN = "apps.cluster-v2mx6.v2mx6.sandbox1062.opentlc.com"

    def ensure_elyra_dirs():
        """Crée les répertoires Elyra nécessaires"""
        dirs = [
            f"{ELYRA_METADATA_DIR}/runtimes",
            f"{ELYRA_METADATA_DIR}/component-catalogs",
            f"{ELYRA_METADATA_DIR}/code-snippets",
            f"{ELYRA_METADATA_DIR}/runtime-images",
        ]
        
        for dir_path in dirs:
            Path(dir_path).mkdir(parents=True, exist_ok=True)
            print(f"✓ Répertoire créé: {dir_path}")

    def create_kubeflow_runtime():
        """Crée la configuration runtime Kubeflow Pipelines comme OpenShift AI"""
        return {
            "display_name": "Data Science Pipelines (Triton Demo)",
            "metadata": {
                "api_endpoint": f"https://ds-pipeline-triton-demo-pipelines-{NAMESPACE}.{CLUSTER_DOMAIN}",
                "api_username": "",
                "api_password": "",
                "cos_endpoint": f"http://minio-api-minio.{NAMESPACE}.svc:9000",
                "cos_username": "minioadmin",
                "cos_password": "minioadmin",
                "cos_bucket": "triton-data",
                "cos_directory": "",
                "tags": ["kubeflow", "pipelines", "triton", "custom-image"],
                "engine": "Argo",
                "auth_type": "NO_AUTHENTICATION",
                "runtime_type": "KUBEFLOW_PIPELINES",
                "api_version": "v1",
                "user_namespace": NAMESPACE,
                "engine_namespace": NAMESPACE,
                "cos_secure": False,
                "disable_ssl_verification": True,
                "cos_auth_type": "USER_CREDENTIALS"
            },
            "schema_name": "kfp",
            "name": "data_science_pipelines"
        }

    def create_runtime_images():
        """Crée la configuration des runtime images disponibles"""
        return [
            {
                "display_name": "Triton Demo - Custom ML/AI Image",
                "image_name": "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/triton-demo-notebook:latest",
                "description": "Image personnalisée avec NumPy, Pandas, Scikit-learn, Triton Client et toutes les bibliothèques ML/AI pré-installées",
                "tags": ["ml", "ai", "triton", "custom", "python3.11"],
                "metadata": {
                    "gpu": False,
                    "cuda": False,
                    "python_version": "3.11",
                    "packages": [
                        "NumPy 2.3+",
                        "Pandas 2.3+",
                        "Scikit-learn 1.7+",
                        "Triton Client 2.59+",
                        "Kubeflow Pipelines 1.8+",
                        "Elyra 3.15.0"
                    ]
                }
            },
            {
                "display_name": "Standard Data Science (Fallback)",
                "image_name": "quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.11-2024a-20240317-6f4c36b",
                "description": "Image standard OpenShift AI pour compatibilité",
                "tags": ["standard", "fallback", "python3.11"],
                "metadata": {
                    "gpu": False,
                    "cuda": False,
                    "python_version": "3.11"
                }
            }
        ]

    def save_metadata(metadata, file_path):
        """Sauvegarde les métadonnées dans un fichier JSON"""
        try:
            os.makedirs(os.path.dirname(file_path), exist_ok=True)
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(metadata, f, indent=2, ensure_ascii=False)
            print(f"✓ Runtime configuré: {file_path}")
            return True
        except Exception as e:
            print(f"✗ Erreur lors de la sauvegarde {file_path}: {e}")
            return False

    def save_runtime_images(runtime_images):
        """Sauvegarde la configuration des runtime images"""
        try:
            runtime_images_dir = f"{ELYRA_METADATA_DIR}/runtime-images"
            os.makedirs(runtime_images_dir, exist_ok=True)
            
            # Sauvegarder chaque runtime image dans un fichier séparé
            for i, runtime_image in enumerate(runtime_images):
                file_path = f"{runtime_images_dir}/runtime_image_{i+1}.json"
                with open(file_path, 'w', encoding='utf-8') as f:
                    json.dump(runtime_image, f, indent=2, ensure_ascii=False)
                print(f"✓ Runtime image configuré: {file_path}")
            
            # Sauvegarder aussi dans un fichier principal
            main_file = f"{runtime_images_dir}/runtime_images.json"
            with open(main_file, 'w', encoding='utf-8') as f:
                json.dump({"runtime_images": runtime_images}, f, indent=2, ensure_ascii=False)
            print(f"✓ Configuration principale des runtime images: {main_file}")
            
            return True
        except Exception as e:
            print(f"✗ Erreur lors de la sauvegarde des runtime images: {e}")
            return False

    def main():
        """Configuration principale du runtime comme OpenShift AI"""
        print("🔧 Configuration automatique du runtime Elyra (méthode OpenShift AI)")
        print("=" * 70)
        
        # Créer les répertoires nécessaires
        ensure_elyra_dirs()
        
        # Créer le runtime Kubeflow comme OpenShift AI
        runtime_config = create_kubeflow_runtime()
        
        # Créer les runtime images
        runtime_images = create_runtime_images()
        
        # Sauvegarder le runtime dans le bon répertoire
        runtime_file = f"{ELYRA_METADATA_DIR}/runtimes/data_science_pipelines.json"
        
        if save_metadata(runtime_config, runtime_file):
            print("\n✅ Configuration du runtime terminée avec succès!")
            print(f"📁 Fichier: {runtime_file}")
            print(f"🔗 Endpoint: {runtime_config['metadata']['api_endpoint']}")
            print(f"📦 Bucket S3: {runtime_config['metadata']['cos_bucket']}")
            print(f"🏷️ Nom du runtime: {runtime_config['display_name']}")
            print(f"⚙️ Engine: {runtime_config['metadata']['engine']}")
            print(f"🔐 Auth Type: {runtime_config['metadata']['auth_type']}")
        
        # Sauvegarder les runtime images
        if save_runtime_images(runtime_images):
            print("\n✅ Configuration des runtime images terminée avec succès!")
            print(f"📦 Nombre d'images configurées: {len(runtime_images)}")
            for img in runtime_images:
                print(f"  - {img['display_name']}: {img['image_name']}")
        
        # Configuration de l'authentification Kubernetes
        setup_kubernetes_auth()
        
        # Vérifier que les fichiers existent
        if os.path.exists(runtime_file):
            print("✅ Le runtime est prêt à être utilisé dans Elyra!")
        else:
            print("❌ Erreur: Le fichier de runtime n'a pas été créé")
            
        runtime_images_dir = f"{ELYRA_METADATA_DIR}/runtime-images"
        if os.path.exists(runtime_images_dir):
            print("✅ Les runtime images sont prêtes à être utilisées dans les pipelines!")
        else:
            print("❌ Erreur: Le répertoire des runtime images n'a pas été créé")

    def setup_kubernetes_auth():
        """Configure l'authentification Kubernetes pour les pipelines"""
        print("\n🔐 Configuration de l'authentification Kubernetes...")
        
        # Vérifier la présence du token de service account
        token_path = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        if os.path.exists(token_path):
            print("✅ Token de service account trouvé")
            try:
                with open(token_path, 'r') as f:
                    token = f.read().strip()
                    print(f"✅ Token chargé (longueur: {len(token)} caractères)")
            except Exception as e:
                print(f"⚠️ Erreur lors de la lecture du token: {e}")
        else:
            print("⚠️ Token de service account non trouvé")
            
        # Vérifier les variables d'environnement Kubernetes
        k8s_host = os.environ.get('KUBERNETES_SERVICE_HOST', 'kubernetes.default.svc')
        k8s_port = os.environ.get('KUBERNETES_SERVICE_PORT', '443')
        print(f"✅ API Kubernetes: https://{k8s_host}:{k8s_port}")
        
        namespace_path = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
        if os.path.exists(namespace_path):
            try:
                with open(namespace_path, 'r') as f:
                    namespace = f.read().strip()
                    print(f"✅ Namespace: {namespace}")
            except Exception as e:
                print(f"⚠️ Erreur lors de la lecture du namespace: {e}")
        else:
                print(f"✅ Namespace configuré: {NAMESPACE}")
            
        print("✅ Configuration d'authentification terminée")

    if __name__ == "__main__":
        main()

  # Configuration Elyra avancée
  jupyter_elyra_config.py: |
    # Configuration Elyra pour les pipelines
    c.ElyraApp.enable_pipeline_editing = True
    c.ElyraApp.runtime_env = 'kubeflow_pipelines'
    
    # Configuration des data connections
    c.ElyraApp.data_connections = {
        'triton-data-connection': {
            'type': 's3',
            'endpoint': 'http://minio-api-minio.svc:9000',
            'access_key': 'minioadmin',
            'secret_key': 'minioadmin',
            'bucket': 'triton-data'
        }
    }
    
    # Configuration des runtime images
    c.ElyraApp.runtime_images = [
        {
            'display_name': 'Triton Demo - Custom ML/AI Image',
            'image_name': 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/triton-demo-notebook:latest',
            'description': 'Image personnalisée avec toutes les bibliothèques ML/AI pré-installées',
            'tags': ['ml', 'ai', 'triton', 'custom', 'python3.11']
        },
        {
            'display_name': 'Standard Data Science (Fallback)',
            'image_name': 'quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.11-2024a-20240317-6f4c36b',
            'description': 'Image standard OpenShift AI pour compatibilité',
            'tags': ['standard', 'fallback', 'python3.11']
        }
    ] 