apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: triton-demo
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: true
  database:
    mariaDB:
      deploy: true
      pvcSize: 10Gi
      pipelineDBName: mlpipeline
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: minio-api.minio.svc
      port: "9000"
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
