apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: triton-demo
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    artifactSignedURLExpirySeconds: 60
    cacheEnabled: true
    pipelineStore: database
  database:
    mariaDB:
      deploy: true
      pvcSize: 10Gi
      pipelineDBName: mlpipeline
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: minio-api.minio.svc:9000
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    deploy: true
    cronScheduleTimezone: UTC
