apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: triton-demo
  labels:
    app.kubernetes.io/name: triton-demo-pipelines
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/part-of: openshift-ai-demo
    app.kubernetes.io/managed-by: gitops
    demo.openshift.ai/type: triton-inference
type: Opaque
data:
  accesskey: bWluaW8=  # minio
  secretkey: bWluaW8xMjM=  # minio123 