apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: triton-demo
spec:
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: true
  database:
    mariaDB:
      deploy: true
      pvcSize: 10Gi
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: minio-api-minio.apps.cluster-v2mx6.v2mx6.sandbox1062.opentlc.com
      port: "443"
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: https
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
