apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-db-credential
  namespace: triton-demo
  labels:
    app.kubernetes.io/name: triton-demo-pipelines
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/part-of: openshift-ai-demo
    app.kubernetes.io/managed-by: gitops
    demo.openshift.ai/type: triton-inference
type: Opaque
data:
  password: cGFzc3dvcmQ=  # password 