apiVersion: v1
kind: Secret
metadata:
  name: triton-demo-s3-connection
  namespace: triton-demo
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/description: 'Connexion S3 vers MinIO pour la démo Triton'
    openshift.io/display-name: 'Triton Demo - S3 Connection'
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_S3_BUCKET: bWxwaXBlbGluZQ==
  AWS_S3_ENDPOINT: bWluaW8tdHJpdG9uLWRlbW8tcGlwZWxpbmVzLnRyaXRvbi1kZW1vLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= 