apiVersion: v1
kind: Secret
metadata:
  name: triton-demo-s3-connection
  namespace: triton-demo
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/description: 'Connexion S3 vers MinIO externe pour la démo Triton'
    openshift.io/display-name: 'Triton Demo - S3 Connection (MinIO Externe)'
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8= # base64 encoded "minio"
  AWS_DEFAULT_REGION: dXMtZWFzdC0x # base64 encoded "us-east-1"
  AWS_S3_BUCKET: bW9kZWwtcmVnaXN0cnktYnVja2V0 # base64 encoded "model-registry-bucket"
  AWS_S3_ENDPOINT: bWluaW8tYXBpLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA= # base64 encoded "minio-api.minio.svc.cluster.local:9000"
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= # base64 encoded "minio123" 