---
# PVC pour le workbench (essentiel)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-workbench-pvc
  namespace: triton-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi

---
# Service Account minimal (essentiel)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: triton-workbench-sa
  namespace: triton-demo
