apiVersion: batch/v1
kind: Job
metadata:
  name: llm-copy-job
  namespace: default
spec:
  template:
    spec:
      nodeName: worker-0  # Spécifier le nœud cible
      initContainers:
      - name: llm-download
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "📥 Téléchargement du LLM..."
          
          # Installer les outils nécessaires
          dnf install -y wget git-lfs tar gzip
          
          # Créer le répertoire de destination
          mkdir -p /opt/llm/models
          cd /opt/llm/models
          
          # Méthode 1: Depuis Hugging Face (nécessite un token)
          # export HF_TOKEN="your_token_here"
          # git lfs install
          # git clone https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
          
          # Méthode 2: Depuis un serveur S3/MinIO
          # dnf install -y aws-cli
          # aws s3 cp s3://my-bucket/llama2-7b.tar.gz .
          # tar -xzf llama2-7b.tar.gz
          
          # Méthode 3: Depuis un serveur HTTP
          wget -O llama2-7b.tar.gz "https://example.com/models/llama2-7b.tar.gz"
          tar -xzf llama2-7b.tar.gz
          rm llama2-7b.tar.gz
          
          echo "✅ LLM téléchargé et extrait"
        volumeMounts:
        - name: llm-storage
          mountPath: /opt/llm
      containers:
      - name: llm-copy
        image: registry.redhat.io/ubi8/ubi:latest
        command: ["/bin/bash"]
        args:
        - -c
        - |
          echo "🔄 Copie du LLM vers le système de fichiers du nœud..."
          
          # Copier vers le système de fichiers du nœud
          cp -r /opt/llm/* /host/opt/llm/
          chmod -R 755 /host/opt/llm
          
          echo "✅ LLM copié vers le nœud"
          
          # Vérifier l'espace disque
          df -h /host/opt/llm
          
          echo "🎉 Opération terminée"
        volumeMounts:
        - name: llm-storage
          mountPath: /opt/llm
        - name: host-storage
          mountPath: /host
          readOnly: false
      volumes:
      - name: llm-storage
        emptyDir: {}
      - name: host-storage
        hostPath:
          path: /
          type: Directory
      restartPolicy: Never
  backoffLimit: 3 