# Opérateurs - Phase 1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: components/operators
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Instances - Phase 2 (après opérateurs)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-instances  
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mouachan/openshift-ai-setup.git
    targetRevision: main
    path: components/instances
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
