apiVersion: batch/v1
kind: Job
metadata:
  name: model-registry-http-annotation
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry
    app.kubernetes.io/component: model-registry-http-fix
    app.kubernetes.io/part-of: openshift-ai
    environment: development
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: model-registry-http-fix
    spec:
      serviceAccountName: model-registry-http-fix
      restartPolicy: OnFailure
      containers:
      - name: annotate-service
        image: quay.io/openshift/origin-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Model Registry service to be ready..."
          while ! oc get service default-model-registry -n rhoai-model-registries >/dev/null 2>&1; do
            echo "Service not found, waiting 10 seconds..."
            sleep 10
          done
          
          echo "Applying HTTP annotation to Model Registry service..."
          oc annotate service default-model-registry -n rhoai-model-registries \
            "routing.opendatahub.io/external-address-rest=default-model-registry.rhoai-model-registries.svc.cluster.local:8080" \
            --overwrite
          
          echo "Annotation applied successfully!"
          oc get service default-model-registry -n rhoai-model-registries -o jsonpath='{.metadata.annotations.routing\.opendatahub\.io/external-address-rest}'
