apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace first
  - ../model-registry-namespace/base
  
  # Database infrastructure
  - ../mysql-model-registry/base
  
  # S3 storage infrastructure  
  - ../minio-s3-storage/base
  
  # Model Registry configuration
  - ../model-registry-config/base

commonLabels:
  app.kubernetes.io/name: model-registry-infrastructure
  app.kubernetes.io/part-of: openshift-ai
  environment: development
