# Configuration Kueue pour RHOAI 2.22
# Gestion des queues pour distributed workloads et CodeFlare

apiVersion: config.kueue.x-k8s.io/v1beta1
kind: Configuration
metadata:
  name: kueue-manager-config
  namespace: kueue-system
spec:
  namespace: kueue-system
  manageJobsWithoutQueueName: true
  internalCertManagement:
    enable: true
  clientConnection:
    qps: 50
    burst: 100
---
# ClusterQueue par défaut pour les workloads
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: default-flavor
      resources:
      - name: "cpu"
        nominalQuota: 10
      - name: "memory"
        nominalQuota: 40Gi
---
# ResourceFlavor par défaut
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
spec: {}
