# Configuration Kueue pour RHOAI 2.22
# Gestion des queues pour distributed workloads et CodeFlare
# Utilise Red Hat build of Kueue 1.0.1

# ClusterQueue par défaut pour les workloads
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: default-flavor
      resources:
      - name: "cpu"
        nominalQuota: 10
      - name: "memory"
        nominalQuota: 40Gi
---
# ResourceFlavor par défaut
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
spec: {}
---
# LocalQueue par défaut pour les projets
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default-queue
  namespace: default
spec:
  clusterQueue: cluster-queue
