# Configuration OpenShift Pipelines pour OpenShift AI 2.22
# Supporte TektonConfig et intégrations Data Science

apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: openshift-pipelines
spec:
  profile: all
  targetNamespace: openshift-pipelines
  addon:
    params:
    - name: clusterTasks
      value: "true"
    - name: pipelineTemplates
      value: "true"
    - name: communityClusterTasks
      value: "true"
  pipeline:
    disable-affinity-assistant: false
    disable-creds-init: false
    disable-home-env-overwrite: true
    disable-working-directory-overwrite: true
    enable-api-fields: stable
    enable-bundles-resolver: true
    enable-cluster-resolver: true
    enable-custom-tasks: true
    enable-git-resolver: true
    enable-hub-resolver: true
    enable-tekton-oci-bundles: false
    metrics.pipelinerun.duration-type: histogram
    metrics.pipelinerun.level: pipelinerun
    metrics.taskrun.duration-type: histogram
    metrics.taskrun.level: taskrun
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: true
    send-cloudevents-for-runs: false
  trigger:
    default-service-account: pipeline
    enable-api-fields: stable
  hub:
    categories:
    - All
    - Build Tools
    - CLI
    - Cloud
    - Code Quality
    - Data Processing
    - Deployment
    - Developer Tools
    - Git
    - Image Build
    - Kubernetes
    - Machine Learning
    - Messaging
    - Monitoring
    - Notification
    - Security
    - Storage
    - Testing
    catalogs:
    - name: tekton
      remote:
        url: https://api.hub.tekton.dev/v1
    scopes:
    - cluster
    - namespace
  platforms:
    openshift:
      pipelinesAsCode:
        enable: true
        settings:
          application-name: "Pipelines as Code CI"
          auto-configure-new-github-repo: "false"
          bitbucket-cloud-check-source-ip: "true"
          custom-console-name: ""
          custom-console-url: ""
          custom-console-url-pr-details: ""
          custom-console-url-pr-tasklog: ""
          error-detection-from-container-logs: "false"
          error-detection-max-number-of-lines: "50"
          error-detection-simple-regexp: "^(?P<filename>[^:]*):(?P<line>[0-9]+):(?P<column>[0-9]+):(.*)"
          error-log-snippet: "true"
          hub-catalog-name: "tekton"
          hub-url: "https://api.hub.tekton.dev/v1"
          remote-tasks: "true"
          secret-auto-create: "true"
          secret-github-app-token-scoped: "true"
