apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mysql-instance
  annotations:
    argocd.argoproj.io/sync-wave: "1"

resources:
- namespace.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- mysql-pvc.yaml
- mysql-secret.yaml
- mysql-user-init.yaml
- mysql-init-script.yaml 