apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: db-ai
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: openshift-ai
    app.kubernetes.io/managed-by: gitops
    environment: development
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # password
  mysql-user: cm9vdA==  # root
  mysql-password: cGFzc3dvcmQ=  # password
  mysql-database: bW9kZWxfcmVnaXN0cnk=  # model_registry 